
name: context_exam

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:      
      #- uses: actions/checkout@v3
      
      - name: "context"
        env:
          COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id => $COMMIT_ID"
      
